Private Event Test
didymus707/private-events pull request #3
Opened 2020-07-14 13:18 UTC by didymus707

Added unit and integration test for the project

2020-07-14 19:43 UTC, wathigo requested changes
### Changes Required
Great work adding unit and integration tests for the application.
Also great work on the styles!

**REQUIRED**
*  Event managment features should have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from Pathwright).

**After implementing the changes, submit another request for review.**

**Happy Hacking :computer: 
Simon Wathigo**

2020-07-14 19:43 UTC, wathigo commented on app/views/partials/_invite_form.html.erb
> +  </div>-->
**REQUIRED**
Let's delete the commented code

2020-07-15 08:42 UTC, maelfosso requested changes
# Changes required :red_circle: 

Thank you for applying the suggested changes.
However, it's not sufficient.

1. You **must check whether or not the test is OK**. Do that by checking the expected result with the really one

2. Write test that also failed.

3- Read the comments below

**CHANGES REQUIRED** :red_circle: 

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

2020-07-15 08:42 UTC, maelfosso commented on spec/features/user_spec.rb
> +    end
What next? You must expect the user to be created into the database and after clicking on the sign up button, a new page appears, routing has been done. you should expect all those things.

2020-07-15 08:42 UTC, maelfosso commented on spec/features/user_spec.rb
> +  end
Same thing here. What is the sign of a successful log in process.

2020-07-15 08:42 UTC, maelfosso commented on spec/features/user_spec.rb
> +  end
Same problem!!!

2020-07-15 23:57 UTC, uryelah commented
Hi **Didymus Orotayo**, I'm Sarah your reviewer for this PR 👩‍🚀 

Great job implementing the suggestions from the last review!

-------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**


---------

    
    
**Keep being awesome devs and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-07-16 05:09 UTC, merged